### PR TITLE
🐞 Dropdown fix - updating options dynamically

### PR DESCRIPTION
**Pull request by tomaskeong**
[JIRA Issue](https://gympass.atlassian.net/browse/TVM-924)

## Description 📄

- This PR is created to fix this opened issue #445 
- Brief issue description: if we send a new list of `options` to the `<Dropdown/>`component and that list contains a selected item, the component does not update accordingly. It updates the options list but not the selected item.
- [IMPORTANT‼️] Check the testing section, where I might need some assistance/guidance to fully test this bug fix

## Platforms 📲

- [X] Web
- [ ] Mobile

## Type of change 🔍

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? 🧪

Alright, so I found it pretty hard to test this bug fix, manually. Ideally, one way to test this fix would be to create an `useEffect` and update the `options` prop that is passed to the component with a new selected item, then validate if the component updated accordingly. Not sure if using `useEffect` is supported inside our documentation markdown (file `drodown-web.mdx`), but I couldn't find a way of doing it. Could you please help me? 😀

FYI, the only manual test that I was able to do was to add an `useEffect` inside the actual `<Dropdown />` component that updated the list options after 3 seconds. It worked... but it's quite inconclusive, since we want to test the usage of the component "from the outside".

Anyway, all the help is much appreciated, thanks!

- [ ] Unit Test
- [ ] Snapshot Test

## Checklist: 🔍

- [X] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
- [ ] Layout matches design prototype: [FIGMA](https://figma.com/file/YOUR_LINK)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

## Screenshots 📸

[Upload your screenshots here]

| Before | After |
| ------ | ----- |
|        |       |

### CODE REVIEW

**Review by chady-chaito — APPROVED** [review]

**Review by matheushdsbr — APPROVED** [review]
LGTM 🚀

**Review by luanlorenzo — APPROVED** [review]

**Comment by matheushdsbr** [comment]
Nice contribution @tomaskeong 🚀

I think it's important to have some way to test this fix before merging, but I'll talk to the team about it

**Comment by matheushdsbr** [comment]
Hey @tomaskeong! 

Could you add a video showing your changes? it would be really cool for us to have a good view of your changes 🚀

**Review by matheushdsbr — APPROVED** [review]

**Comment by matheushdsbr** [comment]
@all-contributors please add @tomaskeong for code

**Pull request merged**
