### PR TITLE
🚀 docs(icons): modularize Icons

### PR DESCRIPTION
**Pull request by matheushdsbr**
## Description 📄

Looking at the icons, I noticed that there were two types of icons, UI icons and flag icons, but they were all in one place.

I thought about modularizing the icons for a clearer and more objective view by separating them into groups, we can facilitate the calling and treatment of some icon lists.

## Platforms 📲

- [x] Web
- [ ] Mobile

## Type of change 🔍

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist: 🔍

- [x] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
- [ ] Layout matches design prototype: [FIGMA](https://figma.com/file/YOUR_LINK)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### Before
image

image

### After
image

image

### CODE REVIEW

**Comment by caiotracera** [comment]
Hey, @matheushdsbr !
Thanks for the PR! As you can see, the CI is broken, but we are working on that.

Anyway, I think that this is a great change, but I'm afraid that this change can be a BREAKING CHANGE. What do you think? If we update the yoga in some project after this change, we will need to change all the icons imports, or will continue working as it is?

**Comment by caiotracera** [comment]
Just a simple update:

* I've pushed the CI fixes to PR #547, so you'll need to sync with the master.
* It seems that the CI in your PR is breaking because he couldn't find your branch in our repo. Can you make your changes in a branch inside the Yoga instead of creating a fork?

Feel free to reach me if you need any help 🫶🏻

**Comment by matheushdsbr** [comment]
> Hey, @matheushdsbr ! Thanks for the PR! As you can see, the CI is broken, but we are working on that.
> 
> Anyway, I think that this is a great change, but I'm afraid that this change can be a BREAKING CHANGE. What do you think? If we update the yoga in some project after this change, we will need to change all the icons imports, or will continue working as it is?

Yo @caiotracera !

The way I put the exports allows the icons that were being used before to continue being imported in the same way, only now with the changes in this PR, in addition to importing individually as it is currently in yoga, we can also import them in a group.

That way I added one more way to import the icons, but keeping the imports as they are being used today.

Thank you for your review! It was a very important point to be discussed o/ 🚀

**Comment by caiotracera** [comment]
Hey, @matheushdsbr!
Congrats for the code and for the initiative, it is very important for us to see the community helping to improve the DS.

Just make sure that the CI is passing, and we'll be able to move forward and merge this pull request 💜

**Comment by matheushdsbr** [comment]
> Just a simple update:
> 
>     * I've pushed the CI fixes to PR [🐞 Fix broken tests in CI #547](https://github.com/gympass/yoga/pull/547), so you'll need to sync with the master.
> 
>     * It seems that the CI in your PR is breaking because he couldn't find your branch in our repo. Can you make your changes in a branch inside the Yoga instead of creating a fork?
> 
> 
> Feel free to reach me if you need any help 🫶🏻

OK! I just synced my fork with master, now it's up to date, thanks for the suggestion! ✌️

**Comment by matheushdsbr** [comment]
> Hey, @matheushdsbr! Congrats for the code and for the initiative, it is very important for us to see the community helping to improve the DS.
> 
> Just make sure that the CI is passing, and we'll be able to move forward and merge this pull request 💜

Alright! I'm happy to contribute, thanks! \o/ 🤝

**Review by guilhermecardoso-gympass — APPROVED** [review]

**Review by caiotracera — APPROVED** [review]

**Comment by caiotracera** [comment]
@all-contributors please add @matheushdsbr for feature

**Comment by caiotracera** [comment]
https://github.com/all-contributors please add @matheushdsbr for code

**Comment by caiotracera** [comment]
@all-contributors please add @matheushdsbr for code

**Pull request merged**
